# config.yaml

models:
  BASE: 
    TextDetection: "models/TextDetection"
  LAMA:
    ckpt: "models/Inpainter/lama/big-lama.ckpt"
    config: "models/Inpainter/lama/config.yaml"

  PATH:
    TextDetection:
      EAST: "frozen_east_text_detection.pb"
      DB50: "DB_TD500_resnet50.onnx"



