# config.yaml

models:
  BASE: 
    TextDetection: "models/TextDetection"
    Inpainter: "models/Inpainter"
  LAMA:
    ckpt: "lama/big-lama.ckpt"
    config: "lama/config.yaml"

  PATH:
    TextDetection:
      EAST: "frozen_east_text_detection.pb"
      DB50: "DB_TD500_resnet50.onnx"



